In [4]:
import numpy as np # 패키지 numpy 를 불러와서 np라고 부르겠다

arr = np.array([1,2,3,4])  # Python List 형식
print(arr)                 # 출력물 = Numpy
print(type(arr))         

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# 0으로 초기화된 배열 생성

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
# 빈 값으로 만들어진 배열??? # 0으로 초기화 시키는 이유
arr1 = np.empty((3,3))
arr2 = np.empty((4,4))
print(arr1)
print(arr2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2.30277911e-316 3.80430547e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.50008929e+248 4.31174539e-096 9.80058441e+252]
 [1.23971686e+224 2.59031995e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 2.66023306e-312 0.00000000e+000]]


In [9]:
# 1로 가득찬 배열 생성
arr = np.ones((3,3))

print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


생성된 배열내 숫자뒤의 점의 의미

항상 실수로 표현가능하다
기본적으로 실수(메모리는 커지지만 같은타입으로 처리속도 증가)

In [10]:
# 배열의 생성
arr = np.arange(10)    #10개 짜리 배열 생성 0~9
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
# ndarray 배열의 모양, 차수, 데이터 타입 확인

arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


숫자 뒤의 점이 없으므로

이 배열은 정수형 배열

-> 배열 생성시 넣은 값 자체가 정수기 때문에

In [12]:
# 전체 배열 모양 확인
arr.shape

(2, 3)

In [13]:
# 배열 차원 확인
arr.ndim

2

In [14]:
# 배열의 데이터 타입
arr.dtype

dtype('int64')

In [15]:
# 배열 데이터 타입 변경
arr_float = arr.astype(np.float64)
arr_float.dtype

dtype('float64')

In [17]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

유니코드 타입이다

In [19]:
 # 문자형을 정수형으로 변경

arr_int = arr_str.astype(np.int64)
arr_int.dtype

dtype('int64')

In [20]:
# ndarray(Numpy 배열)의 연산방법

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [21]:
arr1 + arr2

array([[ 6,  8],
       [10, 12]])

In [22]:
# 명령어로 덧셈
np.add(arr1, arr2)

array([[ 6,  8],
       [10, 12]])

In [23]:
arr1 * arr2

array([[ 5, 12],
       [21, 32]])

In [24]:
# 명령어로 곱셉
np.multiply(arr1, arr2)

array([[ 5, 12],
       [21, 32]])

In [26]:
# ndarray 배열 슬라이싱 하기

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
arr.ndim

2

In [34]:
arr.shape

(3, 3)

In [35]:
arr_1 = arr[:2,1:3]
print(arr_1)

[[2 3]
 [5 6]]


arr(3,3) 배열( 3행 3열짜리)

[:2]:처음부터 0, 1까지 즉 인덱스0,1에 해당하는 행을 가져옴

[1:3] : 인덱스 1, 2에 해당하는 열을 가져옴

In [36]:
arr[0,2] #인덱스 0행, 인덱스 2 호출

3

In [37]:
arr[[0,1,2],[2,0,1]] #인덱스 0, 1, 2행, 인덱스 0행2, 1행0, 2행1 호출
                     #첫번째 = 줄선택, 두번째 = 각줄 인덱스 선택

array([3, 4, 8])

In [38]:
idx = arr > 3
print(idx)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [39]:
print(arr[idx])

[4 5 6 7 8 9]


In [41]:
np.loadtxt(fname='winequality-red.csv',delimiter=';',skiprows=1) #csv 파일 열기(파일지정, 구별자, 첫줄무시) 

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [42]:
#저장하기
redwine = np.loadtxt(fname='winequality-red.csv',delimiter=';',skiprows=1)
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


In [43]:
# 합계

print(redwine.sum())

152084.78194


In [44]:
#평균

print(redwine.mean())

7.926036165311652


합계 평균 작업

데이터 기준 축을 고려해야함

<0번축 기준 합>
sum(axis=0)

<1번축 기준 합>
sum(axis=1)

In [45]:
# 축(axis)
print(redwine.sum(axis=0))

[13303.1       843.985     433.29     4059.55      139.859   25384.
 74302.       1593.79794  5294.47     1052.38    16666.35     9012.     ]


In [46]:
print(redwine.mean(axis=0))

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [47]:
#슬라이싱 처리

redwine[:,0].mean()

8.31963727329581

redwine[:,0]
  <-:->, 0(첫번째 컬럼 선택)

  0번축 평균의 첫번째 데이터와 일치

In [48]:
redwine.max(axis=0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])

In [49]:
redwine.min(axis=0)

array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     ,
       0.99007, 2.74   , 0.33   , 8.4    , 3.     ])

CSV 문서 불러오기
축, 배열 이해
