In [1]:
import sklearn
from sklearn.preprocessing import *
import numpy as np
from numpy import *

In [6]:
def normaliztion(data):
  data_mm = (data - data.min(axis=0))/(data.max(axis=0)-data.min(axis=0))
  return data_mm

def numpy_standardiztion(data):
  """
  (각데이터 - 평균(각열)) / 표준편차(각열)
  """
  std_data=(data - np.mean(data, axis=0)/np.std(data, axis=0))
  return std_data

def main():
  data = np.random.randint(30, size=(6,5))
  #print(data)
  std_data_temp = numpy_standardiztion(data)
  print(std_data_temp)

  no_data = normaliztion(data)
  print(data)

if __name__ == '__main__':
  main()

[[23.47185097  8.55257424  2.42666763 13.29681185 13.86067004]
 [ 1.47185097 27.55257424 19.42666763  4.29681185  8.86067004]
 [19.47185097  2.55257424 10.42666763  6.29681185 -0.13932996]
 [25.47185097  4.55257424 13.42666763  8.29681185 18.86067004]
 [-1.52814903  6.55257424 14.42666763 20.29681185 19.86067004]
 [21.47185097 19.55257424 -1.57333237  1.29681185 11.86067004]]
[[25 10  4 15 16]
 [ 3 29 21  6 11]
 [21  4 12  8  2]
 [27  6 15 10 21]
 [ 0  8 16 22 22]
 [23 21  0  3 14]]


In [ ]:
## 질문

# if __name__ == '__main__':
#   main()