In [36]:
from keras.datasets import mnist

In [37]:
(train_images, train_labels),(test_images, test_labels) = mnist.load_data()

In [38]:
# 구조 살펴보기
train_images.shape

(60000, 28, 28)

In [39]:
len(train_labels)

60000

In [40]:
test_images.shape

(10000, 28, 28)

In [41]:
from keras import models
from keras import layers

# 어떤모델을 사용할지는 신경망에 따라 결정
# 신경망을 나타내는 네트워크, .Sequential 순차적으로 신경망을 만듬
network = models.Sequential()
# 네트워크에 Dense(일반적인 신경망) 추가, 히든층없이 바로 input, output으로 구성
network.add(layers.Dense(512, activation='relu', input_shape=(28*28,))) # 모양은 첫번째 층에서만 결정해주면된다
network.add(layers.Dense(10, activation='softmax'))

In [42]:
# 신경망 완성

network.compile(optimizer='rmsprop',      # optimizer(최적화): 스스로 최적화해 나가는 방법을 결정(가중치, bias 조정)
                loss='categorical_crossentropy',    # loss(손실값): 다중분류에서는 기본적으로 crossentropy(이중에서는 binary)
                metrics=['accuracy']
                )

In [43]:
# 데이터 모양의 변환
train_images = train_images.reshape((60000,28*28))
print(train_images)
print(train_images.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(60000, 784)


In [ ]:
# 데이터 실수형으로 변환
train_images = train_images.astype('float32') / 255

test_images = test_images.reshape((10000, 28*28))
test_images = test_images.astype('float32') / 255

In [45]:
# Categorical Data(분류형 데이터의 설정)
# 예전에 했던 encoding 개념
from tensorflow.keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [46]:
# 네트워크에 학습을 시킴
network.fit(train_images, train_labels,
            epochs = 5,         # epochs = 5, 학습 반복 횟수 
            batch_size = 128    # batch_size = 128, 128Kbite씩 뭉텅이로
            ) 


Epoch 1/5
469/469 [==============================] - 5s 10ms/step - loss: 0.2575 - accuracy: 0.9264
Epoch 2/5
469/469 [==============================] - 4s 10ms/step - loss: 0.1044 - accuracy: 0.9687
Epoch 3/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0689 - accuracy: 0.9793
Epoch 4/5
469/469 [==============================] - 4s 9ms/step - loss: 0.0504 - accuracy: 0.9850
Epoch 5/5
469/469 [==============================] - 5s 10ms/step - loss: 0.0379 - accuracy: 0.9883


In [48]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.0620 - accuracy: 0.9817


In [49]:
print('test_acc: ', test_acc)

test_acc:  0.9817000031471252
